[package]
name = "dbms"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = "1.0"
pest = "2.1"
pest_derive = "2.1"
aes = "0.8.4"
rand = "0.8"
base64 = "0.22.1"
anyhow = "1.0.89"
